openapi: 3.0.3

tags:
  - name: "todo"
    description: "Operations related to TODO items"

info:
  title: TODO Application API
  version: 1.0.0
  description: API for managing TODO items.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: API Support
    url: https://www.example.com/support
    email: support@example.com

servers:
  - url: http://localhost:8080/api

paths:
  /todos:
    get:
      summary: List all TODO items
      operationId: listTodos
      tags:
        - todo
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A list of TODO items
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
          content:
            application/json:
              schema:
                type: array
                maxItems: 100
                items:
                  $ref: '#/components/schemas/Todo'
        '4XX':
          description: Problem with the request
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
    post:
      summary: Create a new TODO item
      operationId: createTodo
      tags:
        - todo
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: The created TODO item
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 10
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /todos/{id}:
    get:
      summary: Get a TODO item by ID
      operationId: getTodoById
      tags:
        - todo
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            maxLength: 36
            format: uuid
      responses:
        '200':
          description: The requested TODO item
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: TODO item not found
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
    put:
      summary: Update a TODO item by ID
      operationId: updateTodoById
      tags:
        - todo
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            maxLength: 36
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: The updated TODO item
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 10
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: TODO item not found
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
    delete:
      summary: Delete a TODO item by ID
      operationId: deleteTodoById
      tags:
        - todo
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            maxLength: 36
            format: uuid
      responses:
        '204':
          description: TODO item deleted
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 10
        '404':
          description: TODO item not found
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          example: '2fb49833-e049-43fc-8687-939de721d93b'
          maxLength: 36
          format: ulid
        title:
          type: string
          example: 'Buy groceries'
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        description:
          type: string
          example: 'Milk, Bread, Cheese'
          maxLength: 255
          pattern: "^[a-zA-Z0-9_-]+$"
        completed:
          type: boolean
          example: false
      required:
        - id
        - title
        - completed
    TodoCreate:
      type: object
      properties:
        title:
          type: string
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        description:
          type: string
          maxLength: 255
          pattern: "^[a-zA-Z0-9_-]+$"
      required:
        - title
    TodoUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        description:
          type: string
          maxLength: 255
          pattern: "^[a-zA-Z0-9_-]+$"
        completed:
          type: boolean 
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key