openapi: 3.0.3

tags:
  - name: "todo"
    description: "Operations related to TODO items"

info:
  title: TODO Application API
  version: 1.0.0
  description: API for managing TODO items.

servers:
  - url: http://localhost:8080/api

paths:
  /todos:
    get:
      summary: List all TODO items
      operationId: listTodos
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: A list of TODO items
          headers:
            X-RateLimit-Limit:
              description: The number of allowed requests in the current period
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                maxItems: 100
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new TODO item
      operationId: createTodo
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: The created TODO item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /todos/{id}:
    get:
      summary: Get a TODO item by ID
      operationId: getTodoById
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            maxLength: 36
            format: uuid
      responses:
        '200':
          description: The requested TODO item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: TODO item not found
    put:
      summary: Update a TODO item by ID
      operationId: updateTodoById
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            maxLength: 36
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: The updated TODO item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: TODO item not found
    delete:
      summary: Delete a TODO item by ID
      operationId: deleteTodoById
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            maxLength: 36
            format: uuid
      responses:
        '204':
          description: TODO item deleted
        '404':
          description: TODO item not found

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          example: '1'
        title:
          type: string
          example: 'Buy groceries'
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        description:
          type: string
          example: 'Milk, Bread, Cheese'
          maxLength: 255
          pattern: "^[a-zA-Z0-9_-]+$"
        completed:
          type: boolean
          example: false
      required:
        - id
        - title
        - completed
    TodoCreate:
      type: object
      properties:
        title:
          type: string
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        description:
          type: string
          maxLength: 255
          pattern: "^[a-zA-Z0-9_-]+$"
      required:
        - title
    TodoUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        description:
          type: string
          maxLength: 255
          pattern: "^[a-zA-Z0-9_-]+$"
        completed:
          type: boolean 